[theme]
primaryColor = "#764ba2"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 100